export const EMPLOYMENT_TYPE = {
  FULL_TIME: 'Full Time',
  PART_TIME: 'Part Time',
  CONTRACTOR: 'Contractor',
};

export const EMPLOYMENT_STATUS = {
  ACTIVE: 'Active',
  ON_LEAVE: 'On Leave',
  TERMINATED: 'Terminated',
};

export const TIMELINE_EVENT_TYPE = {
  PERFORMANCE_REVIEW: 'Performance Review',
  HR_MEETING: 'HR Meeting',
  SALARY_DISCUSSION: 'Salary Discussion',
  WARNING: 'Warning',
  PROMOTION: 'Promotion',
  GENERAL_NOTE: 'General Note',
};

export const EMPLOYMENT_TYPES = [
  EMPLOYMENT_TYPE.FULL_TIME,
  EMPLOYMENT_TYPE.PART_TIME,
  EMPLOYMENT_TYPE.CONTRACTOR,
];

export const EMPLOYMENT_STATUSES = [
  EMPLOYMENT_STATUS.ACTIVE,
  EMPLOYMENT_STATUS.ON_LEAVE,
  EMPLOYMENT_STATUS.TERMINATED,
];

export const TIMELINE_EVENT_TYPES = [
  TIMELINE_EVENT_TYPE.PERFORMANCE_REVIEW,
  TIMELINE_EVENT_TYPE.HR_MEETING,
  TIMELINE_EVENT_TYPE.SALARY_DISCUSSION,
  TIMELINE_EVENT_TYPE.WARNING,
  TIMELINE_EVENT_TYPE.PROMOTION,
  TIMELINE_EVENT_TYPE.GENERAL_NOTE,
];
