export const STRINGS = {
  EMPTY: '',
  GENERIC_ERROR: 'Something went wrong',
  REQUEST_FAILED: 'Request failed',
  RETRY: 'Try again',

  SIGN_IN_TITLE: 'HR System',
  SIGN_IN_SUBTITLE: 'Sign in to manage your company employees',
  SIGN_IN_WITH_GOOGLE: 'Continue with Google',
  SIGN_IN_DEV_HEADING: 'Development sign-in',
  SIGN_IN_DEV_HINT: 'Google sign-in requires a browser redirect. Use this on a simulator or device.',
  SIGN_IN_DEV_EMAIL_PLACEHOLDER: 'you@company.com',
  SIGN_IN_DEV_BUTTON: 'Sign in as developer',
  SIGN_IN_DEV_EMAIL_REQUIRED: 'Enter an email address',
  SIGN_IN_GOOGLE_UNAVAILABLE: 'Google sign-in is not configured',
  SIGN_IN_GOOGLE_CANCELLED: 'Google sign-in was cancelled',
  SIGN_OUT: 'Sign out',

  EMPLOYEES_TITLE: 'Employees',
  SIGNED_IN_AS: 'Signed in as',
  SEARCH_PLACEHOLDER: 'Search by name',
  NO_EMPLOYEES: 'No employees yet',
  NO_SEARCH_RESULTS: 'No employees match your search',

  NAME_INITIAL_SUFFIX: '.',
  PERSONAL_DETAILS: 'Personal details',
  EMPLOYMENT_DETAILS: 'Employment details',
  FIELD_EMAIL: 'Email',
  FIELD_PHONE: 'Phone',
  FIELD_DATE_OF_BIRTH: 'Date of birth',
  FIELD_DEPARTMENT: 'Department',
  FIELD_MANAGER: 'Direct manager',
  FIELD_START_DATE: 'Start date',
  FIELD_EMPLOYMENT_TYPE: 'Employment type',
  FIELD_SALARY: 'Salary',
  NO_MANAGER: '—',
  EDIT_EMPLOYEE: 'Edit',
  VIEW_TIMELINE: 'View timeline',

  NEW_EMPLOYEE_TITLE: 'New employee',
  EDIT_EMPLOYEE_TITLE: 'Edit employee',
  ADD_EMPLOYEE: '+',
  SAVE: 'Save',
  SAVING: 'Saving…',
  CANCEL: 'Cancel',
  SELECT_MANAGER: 'Select manager',
  NO_MANAGER_OPTION: 'No manager',
  FIELD_FIRST_NAME: 'First name',
  FIELD_LAST_NAME: 'Last name',
  FIELD_JOB_TITLE: 'Job title',
  FIELD_EMPLOYMENT_STATUS: 'Employment status',
  REQUIRED_FIELD: 'Required',
  INVALID_EMAIL: 'Enter a valid email address',
  INVALID_DATE: 'Use format YYYY-MM-DD',
  INVALID_SALARY: 'Enter a number of 0 or more',
  DATE_PLACEHOLDER: 'YYYY-MM-DD',

  TIMELINE_TITLE: 'Timeline',
  NEW_TIMELINE_ENTRY_TITLE: 'New entry',
  NO_TIMELINE_ENTRIES: 'No timeline entries yet',
  ADD_TIMELINE_ENTRY: '+',
  FIELD_EVENT_TYPE: 'Event type',
  FIELD_EVENT_DATE: 'Event date',
  FIELD_TITLE: 'Title',
  FIELD_CONTENT: 'Details',
  ENTRY_AUTHOR_PREFIX: 'Logged by',
};
